### ISSUE TITLE
Duration and Start/End Time Problem

### ISSUE THREAD

**Issue by tillmannhartl** [noitcudni/google-takeout-mileage-and-timeline-exporter-extension#1]
Duration = NaN days
Start Time = Invalid date
End Time = Invalid date

**Comment by noitcudni** [comment]
Where are you seeing that?

**Comment by noitcudni** [comment]
Nevermind. I believe you are referring to the Timeline tab.

Are all the rows showing invalid time?
If you don't mind, can you send me your zip file? I'll try to reproduce it
on my end.

Email the zip file to ***@***.***

**Comment by noitcudni** [comment]
I just checked out the code. I don't calculate Duration. It's being read in
from the json file directly.

**Comment by krjamk** [comment]
I am also seeing invalid date, invalid time and duration = nan days. This is on both tabs. I tried various time zones to make sure it wasn't something there causing the issue. Was this every resolved at all? The tool isn't really useful to me without this data.

**Comment by noitcudni** [comment]
Email that to ***@***.***

**Comment by krjamk** [comment]
email sent to the email address in your profile with the file requested. I was doing Chicago for a location and was looking at 2021 date range but tried to shorten to a month as well for testing with no success.

**Comment by jkrime** [comment]
I have the same invalid date, time and duration error. Here's what I've experienced:

I have chosen the dates 2021 January 01 to 2021 December 31, and timezone America/NewYork. I left the times as the default times. I then imported the zip file. When the list populates I only have useable data in the columns From, To, Mode, and Distance. Start Time and End Time display invalid dates for all entries. The From and To display only the Street and house number, not city, state, and zipcode. The bigger issue is none of the rows display any date whatsoever.

**Comment by noitcudni** [comment]
TL/DR - I know the root cause. I'll fix it before I got to bed tonight.

@jkrime @krjamk 
@krjamk Thank you for your zip file. I'm able to reproduce it, and I know what the issue is.

I was expecting the time information is in unix timestamp in milliseconds; however, time's showing up as YYYY-mm-dd hh:mm:ss.

**Comment by noitcudni** [comment]
The bug is fixed. Please wait for version 0.4.0 to get approved by Google.

@jkrime @krjamk, I emailed you guys with additional information separately via email.
