### ISSUE TITLE
Residential Addresses not included in download .cvs

### ISSUE THREAD

**Issue by joovie88** [noitcudni/google-takeout-mileage-and-timeline-exporter-extension#2]
When I import my .zip file to the online view, street addresses are visible, but when I download the csv under milage tab these are just blank.  Looks like it only downloads "name" and not the address.  Any way to keep addresses, maybe if there is no business name?     [EDIT] I guess it's really just my "home" address.  The rest of the addresses seem to be showing up.  I was able to make this work.  
![image](https://user-images.githubusercontent.com/7811837/156417211-4d73dd24-4206-4e83-a8bb-a38ae92e3c76.png)

**Comment by noitcudni** [comment]
Yeah, that's under my radar. I just haven't gotten around to work on it
yet. Thanks for bringing it up to my attention. I should be able to get to
it the next couple of days.

**Comment by noitcudni** [comment]
Hmm, I can't reproduce it on my end. If you are ok with it, can you email me your takeout zip file. My email address is lihster.developer@gmail.com

**Comment by noitcudni** [comment]
I just read through my code. I believe I know what the problem is. Working on a fix now. Never mind sending me your takeout zip file.

**Comment by noitcudni** [comment]
I'm thinking that the downloaded csv will have the location names and their corresponding addresses. Thoughts?

**Comment by noitcudni** [comment]
Just submitted a new version to the Webstore. The new version should be out soon. I'll keep you updated.
