### ISSUE TITLE
Data is not importing

### ISSUE THREAD

**Issue by Creidhne86** [noitcudni/google-takeout-mileage-and-timeline-exporter-extension#3]
I extracted takeout data, but it's not importing when I submit my .zip file via the extension.

Can you add the ability to upload .json files individually?

**Comment by Creidhne86** [comment]
Seems like I caused an issue when I tried to limit the data I was sharing by unzipping, deleting some data and re-zipping.. It still would be nice to import json files individually

**Comment by noitcudni** [comment]
There’s no need to upload them individually as the data is only local to
your browser. I don’t ship the data anywhere else.
