### ISSUE TITLE
Timeline sorted by deviceTag

### ISSUE THREAD

**Issue by b-schlegelii** [noitcudni/google-takeout-mileage-and-timeline-exporter-extension#6]
Is it possible to sort data by "deviceTag"? Two different devices contribute to my location data, and I can differentiate data points in the json file based on device easily, but the exporter does not provide this information. Which would be very helpful, as I only want a copy of my timeline from one device, not both.

**Comment by b-schlegelii** [comment]
> I'll have to take a look. If I understand correctly, the deviceTag data is already in the json files. All I have to do is to expose it. Adding a new deviceTag column should suffice?

Yes that is correct. If you're able to do that it would be so helpful, thank you.

**Comment by noitcudni** [comment]
Adding a deviceTag column in the UI might be too crowded. If I make it into a filterable option, will that work? By the way, deviceTag is just an integer number. Just wanted to double check that I'm looking at the right thing.

Also, I can make it so that the export has the deviceTag info in case you'd like to do something custom on your end.

How does that sound?

**Comment by b-schlegelii** [comment]
> Adding a deviceTag column in the UI might be too crowded. If I make it into a filterable option, will that work? By the way, deviceTag is just an integer number. Just wanted to double check that I'm looking at the right thing.
> 
> Also, I can make it so that the export has the deviceTag info in case you'd like to do something custom on your end.
> 
> How does that sound?

Yes, anything that lets me filter by deviceTag (the integer value so I assume we are looking at the same thing) through your extension or by something custom myself would be perfect!

**Comment by noitcudni** [comment]
I just submitted version 0.9.0. It should be out soon once Google approves it.
You will be able to filter based on the device-tag(s) under the mileage tab. Your downloaded csv will reflect whatever you device to filter by.
